### ISSUE TITLE
change event name in app analytics

### ISSUE THREAD

**Issue by dothework** [dothework/alexa-skill-today-andorid#10]
change the event named _click_ in the app analytics events panel to _ENABLE_

![screen shot 2016-06-21 at 4 27 02 pm](https://cloud.githubusercontent.com/assets/9028552/16245053/04f7298e-37cd-11e6-92c3-c2eb8867c079.png)

**Comment by halfjew22** [comment]
Not sure why this isn't working. I have the code to send an enable event when the enable button is clicked... Will look into it more later.

**Comment by dothework** [comment]
It's working. just want it renamed.

**Comment by halfjew22** [comment]
Can you explain why you think it is? I have code specific to responding to
enable button clicks and its title is enable.

**Comment by dothework** [comment]
because click is vague - enable is clear - it precisely says what caused the
event tick
when we see enable in the analytics dashboard and reports it will not need
interpretation - ie. what freaking click are we talking about???

**Comment by dothework** [comment]
to be clear - I simply want the label of the event in the analytics changed from
click to enable - the code is spot on - it's simply the text that needs to
changed to achieve greater clarity.

**Comment by halfjew22** [comment]
Let me explain better: I misunderstood Firebase analytics and thought we'd have more fields to see in the dashboard. I am already sending what I *thought* was enable to the dashboard, but it's not showing up. That's why I need to look into it more. Does that make sense?

Click was supposed to track a click of literally everything on the screen, including text, images, menus, etc, but it's not working as I expected.

**Comment by halfjew22** [comment]
I *believe* this should be fixed now. We'll see. I spammed the enable button a bunch.

**Comment by halfjew22** [comment]
If enable shows up in the analytics dashboard tomorrow, this worked. Otherwise, I think we've got a beta Mark. I'll send it via email.
